networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "mandrake"
    ports:
      - "3306:3306"
    networks:
      - algafood-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 5s
      timeout: 5s
      retries: 20
      
  algafood-redis:
    image: redis:6.2.1-alpine
    networks:
      - algafood-network          

  algafood-api:
    image: algafood-api
    environment:
      DB_HOST: algafood-mysql
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: algafood-redis
      SPRING_PROFILES_ACTIVE‎: development
    networks:
      - algafood-network
    depends_on:
      algafood-mysql:
        condition: service_healthy
    deploy:
      replicas: 2
      
  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports: 
      - "80:80"
    networks:      
      - algafood-network
    depends_on:
      - algafood-api